ashishb/android-security-awesome

- README.md
Reference the Android Hooker tool as an opensource publicly available dynamic analysis tool for android applications. (I'm the co-author of this tool :) )
> Reference the Android Hooker tool

- README.md
1. Updated link to the AndroGuard project
2. Added link to the StaDynA open-source tool
3. Added section APP REPACKAGING DETECTORS
4. Added link to the FSquaDRA tool
5. Added link to the samples provided by Drebin project
6. Added section BOOKS
7. Added link to the download page of the book Android Security (and Not) Internals
8. Added paired square bracket
> Updated the link, added new links, corrected a typo

- README.md
Added a link to the static analyzer called Amandroid
> Added a link to Amandroid

- README.md
This changeset adds an item to the list of static analysis tools.
> Add link to SPARTA static analysis tool

- README.md
* Move existing tools
* Add Honggfuzz & MFFA tools
* Fixed typo in "radamsa" name
> New FUZZ TESTING category

- README.md
Reading original sequence number under raw model is uncomfortable especially the number order is conflict.
So, why not change the sequence style?
> Change sequence number style

- README.md
The domain name is on sale, I think the developer/company has already given it up.
> Remove app360scan

- README.md
> add radare2

- README.md
Mobile Security Framework is an intelligent, all-in-one open source mobile application (Android/iOS) automated pen-testing framework capable of performing static, dynamic analysis and web API testing.
> Added Mobile-Security-Framework-MobSF

- README.md
Frida is a super useful tool for reverse engineering
> Add Frida to the list

- README.md
Let me know if you need any changes 👍
> Added Appknox and Devknox

- README.md
Added JAADAS in APP VULNERABILITY SCANNERS entry. Thanks.
> Added JAADAS

- README.md
Details of all the android related security issue that includes latest reported issue, how to report an issue, bounty programs etc
> added EXPLOITS / VULNERABILITIES / BUGS section

- README.md
The patch status of different mobiles could easily **help the attacker to determine which exploits would work** on the target device. This information will be very handy during Open Source Intelligence (OSINT) analysis.
> Added Android Devices Security Patch Status from AndroidTamer KB

- README.md
Converted ReadMe into 3 main sections. Transfer READING MATERIAL & TUTORIALS sections to ACADEMIC / RESEARCH / PUBLICATIONS / BOOKS section.
> Formatted ReadMe

- README.md
added AOSP - Issue tracker
strikeout depreciated Vulnerability Google Doc
removed Root Exploits (from Drozer issue #56)
> added AOSP - Issue tracker

- README.md
Lab Automated is an online (SaaS) analyzer that does both static and dynamic analysis
> Move Lab Auto

- README.md
Added the GitHub Repository from tanprathan, which includes a nice Pentest CheatSheet for MobileApps. Sorted it to Others.
> Added Mobile App Pentest Cheat Sheet

- README.md
Added the SUPER Android Analyzer program, which is written in RUST.
> SUPER Android Analyzer

- README.md
This list would be really helpful for people who want to report Android app bugs on bug bounty platforms like HackerOne.
> Added Android Reports and Resources

- README.md
appanalysis.org link was broken with HTTPS. It works with HTTP
> Updated TaintDroid link

- README.md
[StaCoAn](https://github.com/vincentcox/StaCoAn) : A crossplatform tool which aids developers, bugbounty hunters and ethical hackers performing static code analysis on mobile applications. This tool was created with a big focus on usability and graphical guidance in the user interface.
> Add "StaCoAn" in section [Static Analysis Tools]

- README.md
Added an online apk downloader, which I found very useful. The website provides also an own app for downloading apps. Hope it fits to this list. Added it to Misc tools.
> apkpure - Online apk downloader with app

- README.md
I added the direct URL to AMAaaS instead of going through MalwarePot website
> Adding AMAaaS

- README.md
I would like to add vulnerable applications for testing purposes
> add vulnerable applications

- README.md
- run_awesome_bot.sh
> Mark TraceDroid dead

- .travis.yml
- README.md
- run_awesome_bot.sh
Mark www.mobilemalware.com.br and appscan.bluemix.net as dead
> Mark www.mobilemalware.com.br and appscan.bluemix.net as dead

- README.md
support for iOS devices has been added in version 1.4.
Thanks!
Paolo
> update description for Runtime Mobile Security (RMS)

- README.md
Hey @ashishb 
just fixing an URL here.
Cheers,
Peter
> Fix URL for IntentSniffer

- README.md
Android APK Decompilation for the Lazy. Converts apk to java files with one command.
> Adds awesome apkx tool to the list

- README.md
Add a section to add a list of vulnerable android applications for learning purpose
> Add a section for Vulnerable Android applications

- README.md
Hey @ashishb 
just fixing the link for "Dalvik opcodes".
Cheers!
> Updating "Dalvik opcodes"

- README.md
Android Mobile Device Hardening: https://github.com/SecTheTech/AMDH
> Add AMDH to misc tools

- README.md
This work adds Pithus to the list of online analyzers and adds a small description of the project with relevant links.
> Adding Pithus To The List Of Online Analyzers

- README.md
Hi,
I have just added Mobile Audit to Static Analysis tools, it is a web app that does SAST and malware analysis,
Thank you so much
> Add Mobile Audit to Static Analysis

- README.md
AppSweep is a free online application for Android security testing designed to help developers fixing security issues
> Add AppSweep to online analyzers

- .github/workflows/test.yml
- Makefile
- README.md
- run_awesome_bot.sh
Total time taken
1. awesome_bot - 30 mins ([ref](https://github.com/ashishb/android-security-awesome/actions/runs/1821361906))
2. urlsup - 5 mins ([ref](https://github.com/ashishb/android-security-awesome/actions/runs/4528604034/jobs/7975535286?pr=136))
> Use `urlsup` instead of slow `awesome_bot`

- README.md
> Update Pscout link

- README.md
Also, fix formatting in a few places
> Add `dexmod`

- README.md
Free cybercrime intelligence toolset that can indicate if a specific APK package was compromised in an Infostealer malware attack.
> Added Hudson Rock to Malware section

- README.md
Hello, I add HacknDroid A tool designed to automate various Mobile Application Penetration Testing (MAPT) tasks and facilitate interaction with Android devices
> add hackndroid

- README.md
Adds ANY.RUN, an interactive malware analysis [platform](https://app.any.run/). that recently [added support](https://any.run/cybersecurity-blog/android-malware-analysis/) for APK anaylsis.
> Add ANY.RUN (#236)
